version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: chatbot/Dockerfile
    container_name: chatbot_service
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend_service
    ports:
      - "8501:8501"
    depends_on:
      - chatbot
    restart: unless-stopped
