version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: chatbot/Dockerfile
    container_name: chatbot_service
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend_service
    ports:
      - "8501:8501"
    depends_on:
      - chatbot
      - mysql
    environment:
      - DB_HOST=mysql        # Points to mysql container hostname inside network
      - DB_USER=ray
      - DB_PASSWORD=advicr49
      - DB_NAME=music_prediction_db
      - DB_PORT=3306
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql_service
    ports:
      - "3307:3306"          # Maps host port 3307 to container 3306
    environment:
      MYSQL_ROOT_PASSWORD: "advicr49"
      MYSQL_DATABASE: "music_prediction_db"
      MYSQL_USER: "ray"
      MYSQL_PASSWORD: "advicr49"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data:
