version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: chatbot/Dockerfile
    container_name: chatbot_service
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend_service
    ports:
      - "8501:8501"
    depends_on:
      - chatbot
      - mysql # Added dependency on mysql
    environment: # Add this section
      - DB_HOST=mysql # Changed from localhost to mysql
      - DB_USER=ray
      - DB_PASSWORD=advicr49
      - DB_NAME=music_prediction_db
      - DB_PORT=3306
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql_service
    ports:
      - "3307:3306" # Changed host port to 3307
    environment:
      MYSQL_ROOT_PASSWORD: "advicr49"
      MYSQL_DATABASE: "music_prediction_db"
      MYSQL_USER: "ray"
      MYSQL_PASSWORD: "advicr49"
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: